In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
d = pd.read_csv("book.csv")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary
0        two                      8                           9   22000
1       zero                      8                           6   21000
2       five                      6                           7   28000
3        two                     10                          10   25000
4      seven                      9                           6   46000
5      three                      7                          10   34000
6        ten                      6                           7   42000
7     eleven                      7                           8   47000

In [2]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           2                      8                           9   22000
1           0                      8                           6   21000
2           5                      6                           7   28000
3           2                     10                          10   25000
4           7                      9                           6   46000
5           3                      7                          10   34000
6          10                      6                           7   42000
7          11                      7                           8   47000

In [3]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [4]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.predict([[0,5,6]])

array([16033.66568915])

In [6]:
reg.predict([[0,10,10]])

array([23249.26686217])

In [7]:
reg.predict([[3,6,6]])

array([25638.70967742])

In [8]:
reg.predict([[10,10,10]])

array([49733.72434018])